name: Sync to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change relative path to absolute path
        run: sed -i -e 's+../media/+https://beta-programming-in-th.s3-ap-southeast-1.amazonaws.com/solutions/media/+g' *
        working-directory: ./md

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync . s3://beta-programming-in-th/solutions --exclude ".git/* .github/* .gitignore README.md contributing.md LICENSE" --acl public-read
